[colors.primary]
background = '#101417'
foreground = '#e0e3e8'
 
[colors.cursor]
text = '#e0e3e8'
cursor = '#c1c7ce' 
 
[colors.vi_mode_cursor]
text = '#101417'
cursor = '#98ccf9' 
 
[colors.search.matches]
foreground = '#42474d' 
background = '#d0bfe7' 
 
[colors.search.focused_match]
foreground = '#42474d' 
background = '#98ccf9' 
 
[colors.footer_bar]
foreground = '#42474d' 
background = '#e0e3e8' 
 
[colors.hints.start]
foreground = '#42474d' 
background = '#b8c8d9' 
 
[colors.hints.end]
foreground = '#42474d' 
background = '#b8c8d9' 
 
[colors.selection]
text = '#101417'
background = '#98ccf9'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#98ccf9' 
yellow = '#2a638a' 
blue = '#98ccf9' 
magenta = '#d0bfe7' 
cyan = '#b8c8d9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 