[colors.primary]
background = '#0a1519'
foreground = '#d9e4eb'
 
[colors.cursor]
text = '#d9e4eb'
cursor = '#b4cad5' 
 
[colors.vi_mode_cursor]
text = '#0a1519'
cursor = '#5ddbbd' 
 
[colors.search.matches]
foreground = '#354a53' 
background = '#8ad0ee' 
 
[colors.search.focused_match]
foreground = '#354a53' 
background = '#5ddbbd' 
 
[colors.footer_bar]
foreground = '#354a53' 
background = '#d9e4eb' 
 
[colors.hints.start]
foreground = '#354a53' 
background = '#86d6bf' 
 
[colors.hints.end]
foreground = '#354a53' 
background = '#86d6bf' 
 
[colors.selection]
text = '#0a1519'
background = '#5ddbbd'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#5ddbbd' 
yellow = '#006b58' 
blue = '#5ddbbd' 
magenta = '#8ad0ee' 
cyan = '#86d6bf' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 